14 update the component rendering to avoid their overlap in reduced screen size mode
openghg/decc_dashboard pull request #16
Opened 2023-07-31 16:33 UTC by SutarPrasad

- [x] Closes #14 

This PR involved adjusting the overlap of the plot with a clear button
Secondly, the radio MenuIcon in reduced view was not easily visible as its visualisation came out of the header background.
Radio buttons spacing is also adjusted
Y label didn't show the axis name completely in reduced size mode hence updated that too.

2023-07-31 16:42 UTC, SutarPrasad commented
Once react version is upgraded to 18 these checks will resolve. PR 

- [ ] #12

2023-08-10 11:05 UTC, gareth-j commented
For me this makes the select site text move to a weird location
![select_site_text](https://github.com/openghg/decc_dashboard/assets/8915182/25ff4fca-d76b-4cb4-9aa5-4089b32f0e9f)

2023-08-10 11:08 UTC, SutarPrasad commented
> For me this makes the select site text move to a weird location ![select_site_text](https://user-images.githubusercontent.com/8915182/259720016-25ff4fca-d76b-4cb4-9aa5-4089b32f0e9f.jpg)

Ignore this PR it will need to be updated at the end, once all other PR's are merged. Changing to draft.

2023-08-10 11:09 UTC, gareth-j requested changes
Some questions and see screenshot added to the PR.

2023-08-10 11:09 UTC, gareth-j commented on package.json
> +    "@emotion/styled": "^11.11.0",
Are we using emotion anywhere?

2023-08-10 11:09 UTC, gareth-j commented on src/components/ObsBox/ObsBox.js
> +        const yLabel = `Concentration <br>${units}`;
I'm not sure we want a `<br>` here?

2023-08-10 11:09 UTC, gareth-j commented on src/components/ObsBox/ObsBox.js
> +      <div className={styles.container} style={{display:'flex'}}>
Can the style parameters be added to the CSS instead?

2023-08-10 11:09 UTC, gareth-j commented on src/components/RadioButtons/RadioButtons.js
> +      <div className={styles.buttons} onChange={this.onChangeValue} style={{display: "contents"}} >
Add the style parameters to the CSS file instead?

2023-08-18 14:56 UTC, closed without merging