17 add logos to the plot uob metoffice national centre for atmospheric science
openghg/decc_dashboard pull request #20
Opened 2023-08-01 16:07 UTC by SutarPrasad

This PR has added logos to all the available plots

2023-08-07 17:04 UTC, gareth-j commented
For me the tops of the logos are cut off.
<img width="1298" alt="Screenshot 2023-08-07 at 18 04 23" src="https://github.com/openghg/decc_dashboard/assets/8915182/dfb20bcd-0af9-4cb5-a6de-debc97d3e365">

2023-08-07 18:13 UTC, SutarPrasad commented
> For me the tops of the logos are cut off. <img alt="Screenshot 2023-08-07 at 18 04 23" width="1298" src="https://user-images.githubusercontent.com/8915182/258877953-dfb20bcd-0af9-4cb5-a6de-debc97d3e365.png">

Is it after downloading or it's getting rendered like that in the webpage?

2023-08-07 20:35 UTC, SutarPrasad commented
> > For me the tops of the logos are cut off. <img alt="Screenshot 2023-08-07 at 18 04 23" width="1298" src="https://user-images.githubusercontent.com/8915182/258877953-dfb20bcd-0af9-4cb5-a6de-debc97d3e365.png">
> 
> Is it after downloading or it's getting rendered like that in the webpage?

I have shifted the positions of logos little bit below than previous. Please give it a go once again @gareth-j

2023-08-07 20:39 UTC, SutarPrasad commented
<img width="1512" alt="image" src="https://github.com/openghg/decc_dashboard/assets/75735315/2119c106-87a4-4606-a6ed-31270cc00d88">

In SAFARI browser. svg logo inside plot is not loading in firefox hence better we go with .png over there

2023-08-10 11:14 UTC, gareth-j requested changes
Looks good but can we pull out the images list somewhere so it isn't repeated so many times in the code?

2023-08-10 14:54 UTC, SutarPrasad commented
> Looks good but can we pull out the images list somewhere so it isn't repeated so many times in the code?

resolved to use of function instead of list of images.

2023-08-15 07:19 UTC, gareth-j approved these changes
Looks good.

2023-08-15 07:19 UTC, gareth-j commented on src/util/helpers.js
> + * @param {string} source - The image source URL.
Looks good, I like the docstring.

2023-08-15 13:34 UTC, merged