18 allow selection of all the species
openghg/decc_dashboard pull request #21
Opened 2023-08-03 16:02 UTC by SutarPrasad

* **Describe the changes implemented in this PR** (Bug fix, feature, docs update, ...)
  (Short meaningful description)

Here the radio buttons are replaced with dropdown. The speciesLabels JSON file is created to incorporate more species. Currently, its created as a placeholder.

* **Please check if the PR fulfils these requirements**

- [ ] Closes #18 ("Replace xxxx with the Github issue number")
- [ ] [Tests added and passed] if fixing a bug or adding a new feature
- [ ] Documentation and tutorials updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] ESLINT passed

2023-08-07 17:16 UTC, gareth-j requested changes
Just a few questions about the packages and how the species are read.

2023-08-07 17:16 UTC, gareth-j commented on package.json
> +    "@emotion/react": "^11.11.1",
Are we using emotion here?

2023-08-07 17:16 UTC, gareth-j commented on src/components/SelectOptions/SelectOptions.js
> +  componentDidMount() {
We'll be reading this from the data itself so we probably want this as a prop that gets passed through.

2023-08-07 17:16 UTC, gareth-j commented on src/components/SelectOptions/SelectOptions.js
> +  componentDidMount() {
Could we wire it up to the data that's already there for now?

2023-08-07 22:12 UTC, SutarPrasad commented on src/components/SelectOptions/SelectOptions.js
> +  componentDidMount() {
It's kind of doing the same right now. Species labels file helps us to add as many species as we want and if those similar are available in the data it will show in the dropdown, if we do not have them in data but in species, it should not show in Dropdown

2023-08-07 22:14 UTC, SutarPrasad commented on package.json
> +    "@emotion/react": "^11.11.1",
This might be because I was working on something else and had updated the packages

2023-08-10 11:16 UTC, gareth-j commented on src/components/SelectOptions/SelectOptions.js
> +  componentDidMount() {
We should be reading the list of species directly from the data though. As the data is currently structured we'll just need to get the keys of the dictionary (or object in JSON speak) to know which species we'll be plotting.

2023-08-16 10:55 UTC, merged