added download plot functionality to pdf
openghg/decc_dashboard pull request #26
Opened 2023-08-08 22:00 UTC by SutarPrasad

* **Describe the changes implemented in this PR** (Bug fix, feature, docs update, ...)
  Added a Blue download logo with the label: pdf to the bottom right of the Plot. This downloads the plot in pdf format.

* **Please check if the PR fulfils these requirements**

- [ ] Closes #24  ("Replace xxxx with the Github issue number")
- [ ] [Tests added and passed] if fixing a bug or adding a new feature
- [ ] Documentation and tutorials updated/added

- [ ] ESLINT passed

2023-08-10 11:36 UTC, gareth-j requested changes
Looks great! Just a few questions.

2023-08-10 11:36 UTC, gareth-j commented on package.json
> +    "@emotion/react": "^11.11.1",
Sorry to sound like a stuck record, are using emotion here?

2023-08-10 11:36 UTC, gareth-j commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +  handleDownloadPDF = () => {
Would it be possible to export to something like a PNG instead? I think that could be more useful for people wanting to save figures. Or we could give them the option?

2023-08-10 11:36 UTC, gareth-j commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +        pdf.save("concentrationTime_OpenghgPlot.pdf");
Could we create the filename dynamically for the site and species selected?

2023-08-11 08:24 UTC, SutarPrasad commented on package.json
> +    "@emotion/react": "^11.11.1",
yes, usually when styling needs to be applied in react js this package helps

2023-08-11 08:25 UTC, SutarPrasad commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +        pdf.save("concentrationTime_OpenghgPlot.pdf");
yes, nice suggestion

2023-08-11 08:59 UTC, SutarPrasad commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +  handleDownloadPDF = () => {
Matt insisted on pdf with plot size.

2023-08-11 12:17 UTC, SutarPrasad commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +        pdf.save("concentrationTime_OpenghgPlot.pdf");
It can be species and unit but sites can be multiple in that case the file name will be too long, do you think if it will be appropriate?

2023-08-11 15:36 UTC, SutarPrasad commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +        pdf.save("concentrationTime_OpenghgPlot.pdf");
resolved to get filename as species_sitenamesinletHeight

2023-08-15 15:43 UTC, SutarPrasad commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +  handleDownloadPDF = () => {
png plot generated by plotly
![newplot](https://github.com/openghg/decc_dashboard/assets/75735315/cd95cbda-d1b6-4e5b-b7e3-54a4af9a3c7c)

2023-08-18 12:31 UTC, SutarPrasad commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +  handleDownloadPDF = () => {
Added download plot as PNG functionality too.

2023-08-23 11:22 UTC, gareth-j requested changes
Looks good! I think we should just be consistent with our use of `let` and not mix in `var` unless we for some reason need it for a different scope.

2023-08-23 22:21 UTC, SutarPrasad commented on src/components/MultiSiteLineChart/MultiSiteLineChart.js
> +    var filenames = [species, ...sites].join('_');
filenames are only for the scope of the function.

2023-09-01 07:28 UTC, gareth-j approved these changes
Looks good!

2023-09-01 08:37 UTC, merged