28 add obs explainer page
openghg/decc_dashboard pull request #30
Opened 2023-08-16 15:48 UTC by SutarPrasad

* **Describe the changes implemented in this PR** (Bug fix, feature, docs update, ...)
  Added Obs Explainer page and needs updating the text along with the FAQ page.

* **Please check if the PR fulfils these requirements**

- [ ] Closes #28 ("Replace xxxx with the Github issue number")
- [ ] ESLINT passed

2023-08-17 11:04 UTC, gareth-j requested changes
Just a few changes and questions.

2023-08-17 11:19 UTC, SutarPrasad commented on src/Dashboard.js
> +                <Button variant="contained" >
<img width="170" alt="image" src="https://github.com/openghg/decc_dashboard/assets/75735315/209798cd-28fa-4471-aa94-34378f50e12b">

I am in process to update to above view for those

2023-08-17 11:19 UTC, SutarPrasad commented on src/components/FAQ/FAQ.js
> +import styles from "../../Dashboard.module.css";
Yeah, Need to check this, Will get this reverted

2023-08-23 11:35 UTC, gareth-j requested changes
So some changes needed to this one. We should move the changes/restyling of the sidebar out to a separate PR as it doesn't under adding the explainer page. Then just a bit of padding needeed on the FAQ page and the extra route removing.

2023-08-23 11:35 UTC, gareth-j commented on src/Dashboard.js
> -                <Link to="/" className={styles.navLink}>
Keep these links for now but add in the link to the Explainer page.

2023-08-23 22:23 UTC, SutarPrasad commented on .github/workflows/node.js.yml
> +    - run: npm cache clean --force
cleans pre-cached data, incase if there is any old unwanted package that has gotten cached. Sometimes the heap memory can arise from this too.

2023-08-23 22:26 UTC, SutarPrasad commented on src/Dashboard.js
> +              <Route path="/explainer" element={<Explainer></Explainer>}/>
Might have been created inadvertently

2023-08-23 23:13 UTC, SutarPrasad commented on src/components/FAQ/FAQ.js
> +import styles from "../../Dashboard.module.css";
done

2023-08-23 23:15 UTC, SutarPrasad commented on src/components/MyTabs/MyTabs.js
> +import React, { useState } from "react";
done created new PR just for the styling

2023-08-23 23:15 UTC, SutarPrasad commented on src/Dashboard.js
> -                <Link to="/" className={styles.navLink}>
done

2023-08-25 17:42 UTC, rt17603 commented on src/components/Explainer/Explainer.js
> +    const body = `To start with we can use our inventory emissions as our initial “best guess”
```suggestion
    const body = `To start with we can use inventory emissions as our initial “best guess”
```

2023-08-25 17:43 UTC, rt17603 commented on src/components/Explainer/Explainer.js
> +    small changes to the possible emissions and continuously improve to better match the measurements made at each site.
```suggestion
    repeated small changes to the possible emissions to better match the measurements made at each site.
```

2023-08-25 17:44 UTC, rt17603 commented on src/components/Explainer/Explainer.js
> +    The animation below illustrates this process, using a site in Tacolneston, Norfolk which is part of
```suggestion
    The animation below illustrates this process, using the UK DECC network site in Tacolneston, Norfolk.
```

2023-08-25 17:44 UTC, rt17603 commented on src/components/Explainer/Explainer.js
> +    the UK DECC network as an example.`;
```suggestion
```

2023-08-31 21:57 UTC, SutarPrasad commented
> So some changes needed to this one. We should move the changes/restyling of the sidebar out to a separate PR as it doesn't under adding the explainer page. Then just a bit of padding needeed on the FAQ page and the extra route removing.

All of these changes have been addressed and changes are implemented as advised

2023-09-01 08:39 UTC, SutarPrasad commented on src/components/EmissionsBox/EmissionsBox.js
> +    const name = e.target.dataset.onclickparam;
agreed, will make not of this as a new issue.

2023-09-01 08:39 UTC, merged